# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: kt_pubapi_gen_managementv1
output: gopkg/model/generated/management_v1/models.go
generate:
  models: true
output-options:
  # to make sure that all types are generated
  skip-prune: true
  user-templates:
    # we remove the "Merge" method - no need for that in our "oneOf" stuff
    union.tmpl: './go-helper/generator1/customized-templates/union.tmpl'
import-mapping:
  common-types-v2.yaml: 'github.com/keytiles/keytiles-public-api/gopkg/model/generated/common/types_v2'
