openapi: 3.0.1

info:
  version: '1.0'
  title: Common object definitions - regarding scheduled actions.
  description: "These object definitions are shared among multiple contracts. Suitable to describe anything which runs on a scheduled basis - in a very intuitive, human-friendly way. (Unlike chrontab format... :-P)"

paths: {}

components:

  schemas:

    ScheduleDayName:
      type: string
      enum: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
      description: Name of the days we use in day masks.

    Schedule:
      description: 'Describes a Schedule of something. As of now you have basically 4 types: hourly, daily, weekly and Monthly schedules.'
      type: object
      nullable: true
      required:
        - type
        - setup
        - majorVersion
        - tzOffset
      properties:
        type:
          description: Describes which type of schedule is this?
          type: string
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          enum: ['hourly', 'daily', 'weekly', 'monthly']
        setup:
          type: object
          oneOf:
          - $ref: '#/components/schemas/HourlyScheduleSetup'
          - $ref: '#/components/schemas/DailyScheduleSetup'
          - $ref: '#/components/schemas/WeeklyScheduleSetup'
          - $ref: '#/components/schemas/MonthlyScheduleSetup'
        tzOffset:
          type: integer
          description: Encodes the time zone offset from UTC - all things like time and even the days(!) are given using this offset
        majorVersion:
          type: integer
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          description: The major version of the Schedule schema which was used when this object was created. This helps to evolve Schedules over time.

    HourlyScheduleSetup:
      description: Encodes scheduling tailored for hourly execution.
      type: object
      required:
        - firstTime
      properties:
        firstTime:
          type: string
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          nullable: false
          description: >
                      Mandatory element. This is an "HH:MM" formatted time descriptor. Means: within a day what time should we trigger the execution first? From this time the action is shcheduled every hour.  
                        
                      For example if you set it to "09:15" then first execution happens at 09:15, the next one at 10:15 then 11:15 and so on.
          example: '09:15'
        untilTime:
          type: string
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          description: >
                      Optional setting. This is an "HH:MM" formatted time descriptor. Means: within a day triggering will happen only if the current time is <= than this time.  
                        
                      For example, if `firstTime="09:15"` then actually the last execution of the action will happen at "17:15".  
                        
                      In case not given then scheduling will happen within the day every hour starting from `firstTime`.
          example: '18:00'
        dayNames:
          type: array
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          description: Optional setting. If given then scheduling will happen only on these days. This is a day mask basically.
          items:
            $ref: '#/components/schemas/ScheduleDayName'

    DailyScheduleSetup:
      description: Encodes scheduling tailored for daily execution.
      type: object
      required:
        - triggerTime
      properties:
        triggerTime:
          type: string
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          nullable: false
          description: >
                      Mandatory element. This is an "HH:MM" formatted time descriptor. Means: within a day what time should we trigger the execution?
          example: '09:00'
        dayNames:
          type: array
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          description: Optional setting. If given then scheduling will happen only on these days. This is a day mask basically.
          items:
            $ref: '#/components/schemas/ScheduleDayName'

    WeeklyScheduleSetup:
      description: Encodes scheduling tailored for weekly execution.
      type: object
      required:
        - triggerTime
      properties:
        triggerTime:
          type: string
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          nullable: false
          description: >
                      Mandatory element. This is an "HH:MM" formatted time descriptor. Means: within a day what time should we trigger the execution?
          example: '09:00'
        dayName:
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          default: 'Mon'
          $ref: '#/components/schemas/ScheduleDayName'

    MonthlyScheduleSetup:
      description: Encodes scheduling tailored for monthly execution.
      type: object
      required:
        - triggerTime
      properties:
        triggerTime:
          type: string
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          nullable: false
          description: >
                      Mandatory element. This is an "HH:MM" formatted time descriptor. Means: within a day what time should we trigger the execution?
          example: '09:00'
        dayName:
          description: Optional element. To pick up the day when the report is triggered you have a few options. If not given then simply it will be 'firstDay'.
          # we voted against it - let's keep the Nil possibility...
          # x-go-type-skip-optional-pointer: true
          oneOf:
            - $ref: '#/components/schemas/ScheduleDayName'
            - type: string
              enum: ['firstDay', 'lastDay']
          default: 'firstDay'
